import { Routes } from '@angular/router';

import { DashboardComponent } from 'src/app/pages/dashboard/dashboard.component';
import { AgendaComponent } from 'src/app/pages/agenda/agenda.component';
import { AvaliacaoComponent } from 'src/app/pages/avaliacao/avaliacao.component';
import { CategoriaComponent } from 'src/app/pages/categoria/categoria.component';
import { ClienteComponent } from 'src/app/pages/cliente/cliente.component';
import { ClienteFormComponent } from 'src/app/pages/cliente/cliente-form/cliente-form.component';
import { EstoqueComponent } from 'src/app/pages/estoque/estoque.component';
import { FabricanteComponent } from 'src/app/pages/fabricante/fabricante.component';
import { MinhaContaComponent } from 'src/app/pages/minha-conta/minha-conta.component';
import { PedidoComponent } from 'src/app/pages/pedido/pedido.component';
import { PerfilComponent } from 'src/app/pages/perfil/perfil.component';
import { ProdutoComponent } from 'src/app/pages/produto/produto.component';
import { ProdutoFormComponent } from 'src/app/pages/produto/produto-form/produto-form.component';
import { PromocaoComponent } from 'src/app/pages/promocao/promocao.component';
import { ServicoComponent } from 'src/app/pages/servico/servico.component';
import { ServicoFormComponent } from 'src/app/pages/servico/servico-form/servico-form.component';
import { UsuarioComponent } from 'src/app/pages/usuario/usuario.component';
import { UsuarioFormComponent } from 'src/app/pages/usuario/usuario-form/usuario-form.component';
import { VendaComponent } from 'src/app/pages/pedido/venda/venda.component';
import { PedidoDetalheComponent } from 'src/app/pages/pedido/pedido-detalhe/pedido-detalhe.component';
import { NaoEncontradoComponent } from 'src/app/pages/erros/nao-encontrado/nao-encontrado.component';
import { NaoAutorizadoComponent } from 'src/app/pages/erros/nao-autorizado/nao-autorizado.component';

export const AdminLayoutRoutes: Routes = [
    { path: 'dashboard', component: DashboardComponent },
    { path: 'agenda', component: AgendaComponent },
    { path: 'avaliacao', component: AvaliacaoComponent },
    { path: 'categoria', component: CategoriaComponent },
    { path: 'cliente', component: ClienteComponent },
    { path: 'cliente/novo', component: ClienteFormComponent },
    { path: 'cliente/:id', component: ClienteFormComponent },
    { path: 'estoque', component: EstoqueComponent },
    { path: 'fabricante', component: FabricanteComponent },
    { path: 'minha-conta', component: MinhaContaComponent },
    { path: 'pedido', component: PedidoComponent },
    { path: 'venda', component: VendaComponent },
    { path: 'pedido/:id', component: PedidoDetalheComponent },
    { path: 'perfil', component: PerfilComponent },
    { path: 'produto', component: ProdutoComponent },
    { path: 'produto/novo', component: ProdutoFormComponent },
    { path: 'produto/:id', component: ProdutoFormComponent },
    { path: 'promocao', component: PromocaoComponent },
    { path: 'servico', component: ServicoComponent },
    { path: 'servico/novo', component: ServicoFormComponent },
    { path: 'servico/:id', component: ServicoFormComponent },
    { path: 'usuario', component: UsuarioComponent },
    { path: 'usuario/novo', component: UsuarioFormComponent },
    { path: 'usuario/:id', component: UsuarioFormComponent },
    { path: 'nao-encontrado', component: NaoEncontradoComponent },
    { path: 'nao-autorizado', component: NaoAutorizadoComponent },
];
