// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:e254a149-a511-4a08-9dfa-46abf4640c2e",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_PSlQpnVhP",
    "aws_user_pools_web_client_id": "5fg3br218rqrj73e5lql97es63",
    "oauth": {}
};


export default awsmobile;
